apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: argocd-deployer
    namespace: argocd

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-deployer-token
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: argocd-deployer
type: kubernetes.io/service-account-token
