---
- name: Add jetstack helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install certmanager helm package in namespace cert-manager
  kubernetes.core.helm:
    name: cert-manager
    namespace: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{cert_manager.helm_version}}"
    create_namespace: true
    update_repo_cache: true
    values:
      installCRDs: true

- name: Install pre-requisites
  pip:
    name:
      - pyyaml
      - kubernetes

- name: Create staging cluster-issuer for lets encrypt
  kubernetes.core.k8s:
    state: present
    template: cluster-issuer.staging.yml.j2

- name: Create prod cluster-issuer for lets encrypt
  kubernetes.core.k8s:
    state: present
    template: cluster-issuer.prod.yml.j2

- name: Delete cert-manager-webhook
  kubernetes.core.k8s:
    api_version: v1
    kind: ValidatingWebhookConfiguration
    namespace: ingress-controller
    name: "cert-manager-webhook"
    state: absent
